trigger:
- master  # or your branch name

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '18.x'
  app_location: '/'                     # Location of your app source
  output_location: 'build'              # React: build | Angular: dist/<project-name>

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(nodeVersion)'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Install and Build App'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '$(app_location)'
    output_location: '$(output_location)'
    azure_static_web_apps_api_token: '$(deployment_token)' # Set this as a secret pipeline variable
